### ISSUE TITLE
Tidak bisa diinstall untuk php v.8.0 

### ISSUE THREAD

**Issue by SamuelBenedix** [kavist/rajaongkir#21]
[InvalidArgumentException]
 Package kavist/rajaongkir at version 1.1 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

**Comment by putradongkal** [comment]
coba gini:
`composer require kavist/rajaongkir:^1.1 --ignore-platform-reqs`

**Comment by novilmahdi** [comment]
> coba gini: `composer require kavist/rajaongkir:^1.1 --ignore-platform-reqs`

makasih bg

**Comment by imam-syaifudin** [comment]
> coba gini: `composer require kavist/rajaongkir:^1.1 --ignore-platform-reqs`

gg makasih bang sangat  membantu

**Comment by Jukiks45** [comment]
thanks bang

**Comment by Dimasnando** [comment]
makasih bang

**Comment by tarsius2002** [comment]
> coba gini: `composer require kavist/rajaongkir:^1.1 --ignore-platform-reqs`

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

**Comment by Geisha0222** [comment]
> composer require kavist/rajaongkir:^1.1 --ignore-platform-reqs

nice, that work bro, good
